{% set version = "1.4.5" %}

package:
  name: cppcolormap-split
  version: {{ version }}

source:
  url: https://github.com/tdegeus/cppcolormap/archive/v{{ version }}.tar.gz
  sha256: 6cc8e43991cefd0c67d33b7992fd3edf474d7101fd838b98dc7aafdfbbb2b5e6

build:
  number: 0

outputs:

  - name: cppcolormap

    script: install.sh  # [unix]
    script: install.bat  # [win]

    build:
      script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
      host:
        - xtensor
      run:
        - xtensor

    test:
      commands:
        - test -f ${PREFIX}/include/cppcolormap.h  # [unix]
        - test -f ${PREFIX}/lib/cmake/cppcolormap/cppcolormapConfig.cmake  # [unix]
        - if not exist %LIBRARY_PREFIX%\include\cppcolormap.h exit 1 # [win]
        - if not exist %LIBRARY_PREFIX%\lib\cmake\cppcolormapConfig.cmake exit 1 # [win]

  - name: python-cppcolormap

    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]

    build:
      script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
      skip: true  # [python_impl == 'pypy']

    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy *                             # [build_platform != target_platform]
        - setuptools_scm                      # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
        - ninja
      host:
        - numpy *
        - pip
        - pybind11
        - pybind11-abi
        - python
        - scikit-build
        - setuptools_scm
        - xtensor
        - xtensor-python
      run:
        - numpy *
        - python

    test:
      imports:
        - cppcolormap
      commands:
        - pip check
        - python -c "import cppcolormap; assert cppcolormap.version() == '{{ version }}'"
      requires:
        - pip

about:
  home: https://github.com/tdegeus/cppcolormap
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Library with colormaps.
  description: Library with colormaps.
  doc_url: https://tdegeus.github.io/cppcolormap
  dev_url: https://github.com/tdegeus/cppcolormap

extra:
  recipe-maintainers:
    - tdegeus
