{% set name = "cppcolormap" %}
{% set version = "1.3.0" %}
{% set sha256 = "e0097026d68537ef61c253262608d5e0e33784fcb11e301c92b39c02a2aba065" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/cppcolormap/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - xtensor
  run:
    - xtensor

test:
  commands:
    - test -f ${PREFIX}/include/cppcolormap.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/cppcolormap/cppcolormapConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\cppcolormap.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\cppcolormapConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/tdegeus/cppcolormap
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Library with colormaps.
  description: Library with colormaps.
  doc_url: https://github.com/tdegeus/cppcolormap
  dev_url: https://github.com/tdegeus/cppcolormap

extra:
  recipe-maintainers:
    - tdegeus
