{% set name = "cppcolormap" %}
{% set version = "0.2.3" %}
{% set sha256 = "05df1df441d849f8c59915f09f66567bf5cf6cb366d38ee7cb325aa9c4f56b09" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/cppcolormap/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  run:
    - xtensor

test:
  commands:
    - test -f ${PREFIX}/include/cppcolormap.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/cppcolormap/cppcolormapConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\cppcolormap.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\cppcolormapConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/tdegeus/cppcolormap
  license: GPL3
  license_family: GPL3
  license_file: LICENSE
  summary: 'Library with colormaps for C++/Python.'
  description: 'Library with colormaps for C++/Python.'
  doc_url: https://github.com/tdegeus/cppcolormap
  dev_url: https://github.com/tdegeus/cppcolormap

extra:
  recipe-maintainers:
    - tdegeus
